### PR TITLE
Update input params

### PR DESCRIPTION
**Pull request by pshriwise**
This updates the legacy `InputParameter` specification as it is now deprecated (see [here](mooseframework.org/newsletter/2021_11.html#legacy-input-parameter-deprecation))

This fixes the following build error and allows Aurora to be built with the MOOSE `master` branch.

```
/home/pshriwise/opt/aurora/src/moose/framework/build/header_symlinks/MooseTypes.h:485:17: error: static assertion failed: defineLegacyParams is no longer supported as legacy input parameter construction is no longer supported; see mooseframework.org/newsletter/2021_11.html#legacy-input-parameter-deprecation for more information
  485 |   static_assert(false,                                                                             \
      |                 ^~~~~
/home/pshriwise/opt/aurora/src/moose/framework/build/header_symlinks/MooseTypes.h:485:17: note: in definition of macro ‘defineLegacyParams’
  485 |   static_assert(false,                                                                             \
      |                 ^~~~~
```

### CODE REVIEW

**Comment by pshriwise** [comment]
It looks like someone needs to approve the CI run here?

**Comment by helen-brooks** [comment]
Weird, I didn't get a notification for this...

**Comment by helen-brooks** [comment]
I don't know why the CI didn't run automaticallly either. Just tested it with a clean fork and it seems to be running fine. Could you rebase on my latest changes (sorry, it's a big one , but I don't think it should clash with your changes), push and we can see if the CI runs this time?

**Comment by helen-brooks** [comment]
oops, I just found the "approve contributer button", d'oh. Learning more about how github works today. Thanks for rebasing anyway.

**Comment by pshriwise** [comment]
Update: I've added a change from @aprilnovak that corrects the name of a header file to fix a compilation issue we were running into this week.

**Review by helen-brooks — CHANGES_REQUESTED** [review]
The PR as-is is not backwards compatible with the addition of @aprilnovak  changes. However I have locally verified that it's fine in a new docker image, but I have not fully propgated everything to CI.  So, I proposed the following, 
- Roll back to not include the changes to ADOpenMCDensity.h
- I will merge this.
- April changes in separate PR, plus an additional test which fails in the docker I've built
- I will merge this, even though it will fail CI, but it will be clear what is the breaking commit.
- I will open an issue for myself to update CI, and complete this in my own time.
Will this satisfy everyone? Sorry it's taken so long, docker has been a headache

**Review by helen-brooks — APPROVED** [review]

**Pull request merged**
